name: linting, testing, building

on:
  push:
    branches: [ main, develop ]

env:
  HUSKY: 0 # отключаем husky внутри CI

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # -------------------- LINT --------------------
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      - name: Lint TypeScript
        run: npm run lint:ts

      - name: Lint SCSS
        run: npm run lint:scss

  # -------------------- BUILD --------------------
  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      - name: Build production project
        run: npm run build:prod

  # -------------------- TESTS & REPORTS --------------------
  tests-and-reports:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      # Unit tests
      - name: Run unit tests
        run: npm run test:unit

      # Screenshot tests
      - name: Cache Storybook build
        id: storybook-cache
        uses: actions/cache@v4
        with:
          path: storybook-static
          key: >-
            ${{ runner.os }}-${{ matrix.node-version }}-storybook-
            ${{ hashFiles('package-lock.json', '**/*.stories.@(js|jsx|ts|tsx|mdx)') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-storybook-

      - name: Build Storybook
        if: steps.storybook-cache.outputs.cache-hit != 'true'
        run: npm run storybook:build

      - name: Serve storybook static
        run: |
          npx http-server ./storybook-static -p 6006 >/tmp/storybook.log 2>&1 &
          npx wait-on http://localhost:6006

      - name: Run screenshot tests
        run: npm run test:ui:ci

      - name: Generate HTML report
        if: always()
        run: npm run test:ui:report

      - name: Move screenshot report and .loki into reports
        if: always()
        run: mv .loki reports/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Show deployed URL
        run: echo "Report published at ${{ steps.deployment.outputs.page_url }}"

